---
ID: "d339b947-3788-4eb8-97d7-978d19a4fd30"
Parent: "032a58e4-d703-46be-b458-a1af035bc1eb"
Template: "032a58e4-d703-46be-b458-a1af035bc1eb"
Path: /sitecore/templates/Project/Demo/Backoffice/Rendering Parameters/Official Manager Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3c55225a-b3ad-4643-9b43-3ff313f0b820"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\williker.c.carmo@noesis.pt
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240812T150557Z
